baseURL = 'https://lzspriv.github.io'
languageCode = 'zh-tw'
title = 'Sam'
theme = "PaperMod"
buildDrafts = false 

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30

[params.profileMode]
enabled = true
title = "Enter the Content"
subtitle = "Enter the Content"
imageUrl = "img/name.jfif"
imageWidth = 120
imageHeight = 120
imageTitle = "Enter the content"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/SamLiu.06"
[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/zx._.1125/"
[[params.socialIcons]]
name = "discord"
url = "https://discord.com/users/653578637534035968"
[[params.socialIcons]]
name = "github"
url = "https://www.github.com/lzspriv/"

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視
